version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Mursalin-Devops/tomcat-app/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  first-job:

    executor: my-custom-executor
    steps:
      - checkout
      - run: https://github.com/Mursalin-Devops/tomcat-app.git
    steps:
      - build
      - run: sudo -S docker build -t tomcat-app:latest   
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - first-job