version: 2.1

jobs:
  deploy:
    machine: true
    steps:
      
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1c:4a:4f:dd:26:3b:36:fd:6c:32:5a:59:6e:6e:8f:47"
      - run:
          name: Sending Dockerfile To Ansible Server
          command: pwd ; ls ;
      - run:
          name: build docker images
          command: ssh -o StrictHostKeyChecking=no mursalin@172.31.13.103 docker build -t new-app:${CIRCLE_BUILD_NUM} .
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample:
    jobs:
      - deploy
